title: s0ksy@root:~$
description: "hola que tal"
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

# Navegaci√≥n
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Writeups
    url: /writeups/
